name: sentiment-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow=2.8
  - pandas=1.3
  - numpy=1.21
  - matplotlib=3.4
  - seaborn=0.11
  - scikit-learn=1.0
  - jupyter=1.0
  - nltk=3.6
  - pip=21.2
  - pip:
    - wordcloud>=1.8.0
    - textblob>=0.15.0
    - plotly>=5.0.0